fix redgifs
fapinstructor/fapinstructor-client pull request #102
Opened 2023-09-28 19:29 UTC by rororosi

## Proposed changes

RedGifs no longer allows using direct links. I changed the behavior of searchRedGifs to take in an id from fetchRedditPics and return a signed url. 

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

Apologies for not using Axios. I'm relatively unfamiliar with it and it seemed slightly overkill for this use case. If this is a problem feel free to change it, the general fundamentals should remain. searchRedGifs() now takes an ```id: string``` and returns a ```MediaLink``` rather than a ```MediaLink[]```. fetchRedditPics() takes the same input but loops through ```res.links``` to see if they're a redGifs video. If they are change the link to an updated ```MediaLink``` with a signed url as a directLink.

2023-10-02 15:53 UTC, thefapinstructor requested changes
This is great! Thank you for fixing this up.  I added one small comment to enhance performance but overall LGTM

2023-10-02 15:53 UTC, thefapinstructor commented on src/game/xstate/api/fetchRedditPics.ts
> +
Lets update this snippet so that it resolves all redgifs asynchronously  instead of await for each iteration.  It should make it several times faster!

```suggestion
  const redGifLinks = await resolveRedgifsLinks(
    res.links.filter((link) => link.directLink.includes("redgifs"))
  );
  const links = res.links.filter(
    (link) => !link.directLink.includes("redgifs")
  );

  return [...links, ...redGifLinks];

```

```ts
// Asynchronously resolve signed urls for redgif links.
async function resolveRedgifsLinks(redGifLinks: MediaLink[]) {
  const redgifsSignedLinksPromise = await Promise.allSettled(
    redGifLinks.map((link) => {
      const redGifID = link.directLink.split("/")[3].split("-")[0];
      return searchRedGifs(redGifID.toLowerCase());
    })
  );

  const redgifsSignedLinks = redgifsSignedLinksPromise
    .filter(
      (linkPromise): linkPromise is { status: "fulfilled"; value: MediaLink } =>
        linkPromise.status === "fulfilled"
    )
    .map((link) => link.value);

  return redgifsSignedLinks;
}
```

2023-10-02 23:16 UTC, rororosi commented on src/game/xstate/api/fetchRedditPics.ts
> +
This is awesome! Thank you! Just added your changes :)

2023-10-03 02:04 UTC, thefapinstructor submitted a review, later dismissed

2023-10-04 00:53 UTC, thefapinstructor commented
Hey @rororosi , I don't think this will work when deployed.  It looks like the redgifs api is blocked by cors on any other port than localhost:3000 :cry:

2023-10-06 20:41 UTC, rororosi commented
@thefapinstructor is the cors error coming up when we try to get a temp token or when we try to get signed urls? maybe we can make an api route in the [fapinstructor-api](https://github.com/fapinstructor/fapinstructor-api) to do this for us?

2023-10-07 18:57 UTC, thefapinstructor commented
> @thefapinstructor is the cors error coming up when we try to get a temp token or when we try to get signed urls? maybe we can make an api route in the [fapinstructor-api](https://github.com/fapinstructor/fapinstructor-api) to do this for us?

The temp token works but the signed url is where cors has the issue.  I think for the api to be able to generate the signed url it would need to use the users ip but I was never able to get that to work.  Maybe you might have better luck?

2023-10-09 00:25 UTC, rororosi commented
> > @thefapinstructor is the cors error coming up when we try to get a temp token or when we try to get signed urls? maybe we can make an api route in the [fapinstructor-api](https://github.com/fapinstructor/fapinstructor-api) to do this for us?
> 
> The temp token works but the signed url is where cors has the issue. I think for the api to be able to generate the signed url it would need to use the users ip but I was never able to get that to work. Maybe you might have better luck?

It looks like there isn't a work around for it see: https://github.com/Redgifs/api/wiki/Temporary-tokens 
We'll need to make a route in the api to request a jwt token and refresh it every 24 hours see: https://github.com/Redgifs/api/wiki/Client-tokens
I don't know if I can request this on behalf of fapinstructor but here's the form to fill out: https://docs.google.com/forms/d/e/1FAIpQLSf-jnx_BA_y_I3cASpSDrh8dxS18a0r56Bp1T5fTNj7JI4b2g/viewform?hl=en

I'm going to close this PR for now because this doesn't seem like a viable approach.

2023-10-09 00:25 UTC, closed without merging