Fix math errors in handy util (#77)
fapinstructor/fapinstructor-client pull request #79
Opened 2021-12-04 11:13 UTC by wakarimasent

Fix math errors in handy utility

## Proposed changes

Stroke zone was computed incorrectly.
Also, update the tests

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

2021-12-04 11:14 UTC, wakarimasent commented
I'm not sure, how to assign this pull request to issue #77

2021-12-04 11:15 UTC, wakarimasent commented
I'm also unable to run the tests locally. But I've updated the tests with the values which I believe are now correct.

2021-12-05 12:42 UTC, thefapinstructor commented
Thanks @wakarimasent for the PR!  I'll be testing out the changes with the Handy Monday morning.

2021-12-06 19:02 UTC, thefapinstructor commented on src/features/handy/utils/getStrokeSpeedAndDistance.ts
>        ((maxStrokeLength - stroke) / maxStrokeLength) * 100
I think we'll also need to adjust the zone as well.  If the bps = 4, then then stroke will be 100.  That means we are only stroking 50% of the entire strokable area.   

I think this should work, what do you think @wakarimasent?
```
    strokeZone.min = Math.trunc((maxStrokeLength - stroke) / 2);
```

2021-12-06 19:29 UTC, wakarimasent commented on src/features/handy/utils/getStrokeSpeedAndDistance.ts
>        ((maxStrokeLength - stroke) / maxStrokeLength) * 100
No. bps = 4 is around twice as fast as maximum bps (400/195 currently). Therefore, the stroke must be half the max stroke, which is around 100. This is correct.

Also, your proposal sets mm in the percentage field (min is from 0 to 100%), stroke and maxStrokeLength are both in mm (from 0 to 195). The current code, which divides mm by mm and scales this to 100% is correct.

2021-12-06 19:31 UTC, wakarimasent commented on src/features/handy/utils/getStrokeSpeedAndDistance.ts
>        ((maxStrokeLength - stroke) / maxStrokeLength) * 100
I think I might've misunderstood you question. The answer is still no. For bps =4 the stroke is 100 and current strokeZone.min will be (195-100)/195*100 ~ 50. This is correct.

2021-12-07 12:29 UTC, thefapinstructor commented on src/features/handy/utils/getStrokeSpeedAndDistance.ts
>        ((maxStrokeLength - stroke) / maxStrokeLength) * 100
I think you're right.  Not sure why when I tested it the faster speeds didn't work.  I'll give it another test today.

2021-12-09 12:50 UTC, thefapinstructor commented on src/features/handy/utils/getStrokeSpeedAndDistance.ts
>        ((maxStrokeLength - stroke) / maxStrokeLength) * 100
Test it out again and it works perfectly.  Thank you.

2021-12-09 12:57 UTC, thefapinstructor requested changes
Just a couple tweaks to the test assertions.  Once updated I can merge.  Thank you for your contribution!

2021-12-09 12:57 UTC, thefapinstructor commented on src/features/handy/utils/getStrokeSpeedAndDistance.test.ts
> +    expect(strokeZone).toEqual({ min: 70 max: 100 });
Missing a comma between min and max.

2021-12-09 12:57 UTC, thefapinstructor commented on src/features/handy/utils/getStrokeSpeedAndDistance.test.ts
> +    expect(strokeZone).toEqual({ min: 74, max: 100 });
Some minor adjustments to make the tests pass.

```
expect(stroke).toBeCloseTo(49);
```

2021-12-09 12:57 UTC, thefapinstructor commented on src/features/handy/utils/getStrokeSpeedAndDistance.test.ts
> +    expect(stroke).toBeCloseTo(80);
```
expect(stroke).toBeCloseTo(79);
```

2021-12-09 12:57 UTC, thefapinstructor commented on src/features/handy/utils/getStrokeSpeedAndDistance.test.ts
> +    expect(stroke).toBeCloseTo(100);
```
expect(stroke).toBeCloseTo(99);
```

2021-12-09 18:58 UTC, wakarimasent reviewed
I've made a terrible mistake of deleting the forked repository I had made (I tried to edit the code in the browser, since I hadn't a suitable computer to check things out locally.

Now I can checkout this PR and fix the mistakes, but I can't push it anywhere.

Do you mind trying to update it?

2021-12-10 12:08 UTC, thefapinstructor commented
> I've made a terrible mistake of deleting the forked repository I had made (I tried to edit the code in the browser, since I hadn't a suitable computer to check things out locally.
> 
> Now I can checkout this PR and fix the mistakes, but I can't push it anywhere.
> 
> Do you mind trying to update it?

Done!  Created a new https://github.com/fapinstructor/fapinstructor-client/pull/81 with these changes and the updated tests.

2021-12-10 12:08 UTC, closed without merging