Added Copy to clipboard and Save text file of the bookmarks.
fapinstructor/fapinstructor-client pull request #98
Opened 2022-03-14 22:00 UTC by EroticRide

## Proposed changes

Added 2 buttons in the ending screen: 

1. **Copy to Clipboard**: copies all your links of your bookmarks into your device's clipboard
2. **Save text file**: downloads a txt file to your device with all the bookmarks.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Other (please describe):

2022-03-15 12:01 UTC, thefapinstructor requested changes
Thanks for your PR! :pray: :tada:.  I left a couple of small refactor suggestions, once ready I can merge!

2022-03-15 12:01 UTC, thefapinstructor commented on src/features/end/routes/End.tsx
> +    element.download = "fapInstructorBookmarks_" + dateStr + ".txt";
```suggestion
    element.download = `fapinstructor_bookmarks_${format(Date.now(), "yyyy_MM_dd")}.txt`
```

2022-03-15 17:50 UTC, EroticRide commented on src/features/end/routes/End.tsx
> +    alert('Bookmarks copied');
Just changed that in my most recent commit.

2022-03-15 18:11 UTC, EroticRide commented
Just changed the alert box in my most recent commit. 

However, the other two changes you suggested don't seem to work.

1. The way to collect the bookmarks you suggested returns an array of objects. So when you copy/download shows as follows: 
![Bookmark1](https://user-images.githubusercontent.com/98433498/158442525-2f622c47-a08e-4490-ab25-e0d0ba74df27.png)
2. The function you suggested to use for the date formatting doesn't exist in the project and won't compile because of it. Also In my example the time of the day is also included. (For the people that may want to play multiple games a day 😅  )

2022-03-15 23:30 UTC, thefapinstructor commented
> Just changed the alert box in my most recent commit.
> 
> However, the other two changes you suggested don't seem to work.
> 
> 1. The way to collect the bookmarks you suggested returns an array of objects. So when you copy/download shows as follows:
>    ![Bookmark1](https://user-images.githubusercontent.com/98433498/158442525-2f622c47-a08e-4490-ab25-e0d0ba74df27.png)
> 2. The function you suggested to use for the date formatting doesn't exist in the project and won't compile because of it. Also In my example the time of the day is also included. (For the people that may want to play multiple games a day sweat_smile  )

1. I forgot that bookmarks is an object.  You should be able to do something like
```ts
await navigator.clipboard.writeText(store.game.bookmarks.map(bookmark => bookmark.href).join("\n")
```
2. `format` is exported from the wonderful library [date-fns](https://date-fns.org/)
```
import format from "date-fns/format";
```

2022-03-16 00:27 UTC, EroticRide commented
> 

All done, thanks for the help 👍

2022-03-16 13:20 UTC, thefapinstructor approved these changes
LGTM! Thanks for your contribution :heart:

2022-03-16 13:22 UTC, merged